# Generated by Django 4.1 on 2024-01-16 19:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PD", "Pending"),
                            ("CF", "Confirmed"),
                            ("DD", "Delivered"),
                            ("CD", "Canceled"),
                        ],
                        default=("PD", "Pending"),
                        max_length=20,
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="UA"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "receiving",
                    models.CharField(
                        choices=[("DV", "Delivery"), ("SP", "Self pickup")],
                        default=("DV", "Delivery"),
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("promo_code", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "billing",
                    models.CharField(
                        choices=[("CC", "Credit card"), ("CH", "Cash")], max_length=20
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("building", models.CharField(max_length=255)),
                ("apartment", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_quantity", models.IntegerField(default=1)),
                (
                    "ingredients",
                    models.ManyToManyField(
                        blank=True, related_name="ingredients", to="product.ingredient"
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="orders",
                        to="order.cartorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="products",
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cartorder",
            name="cart",
            field=models.ManyToManyField(
                related_name="orders", to="order.orderproduct"
            ),
        ),
    ]
