# Generated by Django 4.1 on 2024-01-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart",
        ),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ManyToManyField(related_name="cart", to="order.orderproduct"),
        ),
    ]
