# Generated by Django 4.1 on 2024-01-17 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_orderproduct_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="order_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="orders",
                to="order.cartorder",
            ),
        ),
    ]
